language: java
cache:
  directories:
    - $HOME/.m2

# do not build on tagged commits to avoid infinite loops
if: tag is blank

#services:
#  - docker

env:
  global:
    # GITHUB_OAUTH_TOKEN=<token>
    - secure: "wiQ9KeD2WfFUrct+VdKjBi83K2S2muy8CT+MqbgpK/hDuIFluUBPz4lDCXBS8dtk1pwE7Zz9Zlu15QZO4SvEFH73QmzseTnaW8E51PCtzih/8AY9X34g1SYqkYZehixPMmDRknhHn+VocZjGJW9GhKqta34viz3WPi6MRqdtsMYR6gf3FXz8HBJbqVHJU0nOdeUzIM4MG674TFupm66t8QtilCLEWwWM0/aSvWAEMFLrHJUehJOe2IakRnMYD07BKIluBG46oUszZ11FXuWGHLKZTgz7FYavCiyT6HMjFI5p5Tpn42FLUz6GGFZ2xWYSc7oXT//eNWVy6lvGK8OvNmo6iPF2e5hfUqdVrPfKW72PwmCnSJqMyQRCWcfyop15sykiS4ThMXXBeo1QxAlVDU1+BMF/Dx9Ho+AEd3jOLnkpmfc/WWpODDrmrM0b2WvcVpIbMZV7dKVt9sV/LIV1f7TvWhUP6TfXhowPjGVN1SoQ6oWzI1e7ibxWkADMIX/sUIqWgC7FSgN+KIHBC3pFonx+peFesLDXZmu1aeXQZ8pC7GiWUhfNQlEz2Cyz70GGYQ2YN478pganfvyDo0ynPrc2fvsNEg/6TGCif9xAzIK+gRFY5qrOZpoAZ6yg9U8YWqX9EQRRK20WMiCAH+A90plnD0qYEWkvYeKHkYNFPD0="
#    - secure: "encrypted DOCKER_USERNAME=user"
#    - secure: "encrypted DOCKER_PASSWORD=pass"
      
stages:
  - test
  - name: deploy_edge
    if: type = push && tag is blank

script: skip
  #- mvn verify -B -P integration-test

matrix:
  include:
  # tests
  - jdk: openjdk8
    stage: test
  - jdk: oraclejdk9
    before_install:
        # The OpenJDK9's CA bundle is outdated, so we're using the system's ones.
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  - jdk: openjdk11
  - jdk: openjdk12
  - jdk: openjdk13
  
  # deploy jobs
  - name: "Deploy Edge Release"
    stage: deploy_edge
    jdk: openjdk8
    before_script:
      - export PROJECT_MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - export TRAVIS_TAG=${TRAVIS_TAG:-$PROJECT_MAVEN_VERSION+$(date +'%Y%m%d%H%M%S')-$TRAVIS_COMMIT}
      - echo $TRAVIS_TAG
    script: skip
      #- mvn package -DskipTests -Dcheckstyle.skip=true
      #- docker build -f install/docker/Dockerfile -t airsonic/airsonic:latest -t airsonic/airsonic:edge/$TRAVIS_TAG .
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Airsonic Travis CI"
      - git config --local user.email "builds@travis-ci.org"
      - git tag "$TRAVIS_TAG" -a -m "Generated tag $TRAVIS_TAG from Travis CI for build $TRAVIS_BUILD_NUMBER"
    deploy:
    - provider: releases
      api_key:
        secure: "I0aBwJhFlCjXmsVFffUMbR38wHp+HrsTBkYKePxWn5+prYgq+9dSz0IjWpHEszUdnCDQcHEJR4nFS2YLEBdEzC4sqkWZVpJEnSVF/izEbxjxb1fNdLeCqZAPkuqw5/pta9JKwdwFMvBLKkV+lBaXscr/sLipAtOIESs+EV1zP5GU0636s4IWA85yfrhKEgE2cjQqtgpbcIZXJWbZN+MtmAhSgeKvUzYGTjOFmF/xfO3ksBAAUd3j0bmsAgA/9+I5XCsR/IRW/PLLdi2ocwsHY+VqdrH4p5kHN3EV2MrjtvhbrRYRFdRoYcux5EXupdTOIMz03GW4wbPJm90hKa2BbaWkzHF9hv6X5boPFrOP+7XqW01X7FVp9dGringEv8CPd+iNPqJLrISDjztnWVuRxpcoJbKEaObYR3DXNyQJ5nbGlrp8vmqRPC2nIJT6UqgE2Bqcap4a1NBVXVQ/zjCCJbDv44QGYWGCL0WIbxOvsWKWvd1otqHi07x8nOAhivoBI44q7UGIoGg0BTs8+EXbbpoAu4cNgLteipByEdtoXnYA7P+L3QLR7kBY5Qyc0bwI2UyE9JlxJMb/90701DMCcKuzvW14aEsVeu00j53UEUCV+i2lKMBZf67VIFQuUvgtUhzzJcvlMaElqh8OrPImRhUkMV9HMY2+qyrHc5CucDg="
      file: airsonic-main/target/airsonic.war
      skip_cleanup: true
      options:
        - prerelease: true
        - name: "Edge Release $TRAVIS_TAG"
      #on:
        #tags: false
        #all_branches: true
    #- provider: script
    #  script: bash install/docker/dockerhub_push.sh
