language: java
cache:
  directories:
    - $HOME/.m2

#services:
#  - docker

#env:
#  global:
#    - secure: "encrypted DOCKER_USERNAME=user"
#    - secure: "encrypted DOCKER_PASSWORD=pass"
      
stages:
  - name: deploy_edge
    # deploy only on commits to master branch
    if: branch = master && type = push

script:
  - mvn verify -B -P integration-test

matrix:
  include:
  # tests
  - name: coverity
    script:
      - echo "coverity scan script"
    install:
      - echo "coverity scan install"
    addons:
      coverity_scan:
        project:
          name: "airsonic-advanced/airsonic-advanced"
          description: "A Free and Open Source community driven media server"
        notification_email: "airsonicadvanced@gmail.com"
        build_command_prepend:
        build_command: mvn -B -q clean package -DskipTests=true
        branch_pattern: master
  - jdk: openjdk8
  - jdk: oraclejdk9
    before_install:
        # The OpenJDK9's CA bundle is outdated, so we're using the system's ones.
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  - jdk: openjdk11
  - jdk: openjdk12
  - jdk: openjdk13
  
  # deploys
  - stage: deploy_edge
    name: "Deploy Edge Release"
    jdk: openjdk8
  before_script:
    - export PROJECT_MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - export TRAVIS_TAG=${TRAVIS_TAG:-$PROJECT_MAVEN_VERSION+$(date +'%Y%m%d%H%M%S')-$TRAVIS_COMMIT}
    script:
      - mvn package -DskipTests -Dcheckstyle.skip=true
      #- docker build -f install/docker/Dockerfile -t airsonic/airsonic:latest -t airsonic/airsonic:edge/$TRAVIS_TAG .
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Airsonic Travis CI"
      - git config --local user.email "airsonicadvanced@gmail.com"
      - git tag $TRAVIS_TAG -m "Edge Release $TRAVIS_TAG"
    deploy:
    - provider: releases
      api_key:
        secure: "I0aBwJhFlCjXmsVFffUMbR38wHp+HrsTBkYKePxWn5+prYgq+9dSz0IjWpHEszUdnCDQcHEJR4nFS2YLEBdEzC4sqkWZVpJEnSVF/izEbxjxb1fNdLeCqZAPkuqw5/pta9JKwdwFMvBLKkV+lBaXscr/sLipAtOIESs+EV1zP5GU0636s4IWA85yfrhKEgE2cjQqtgpbcIZXJWbZN+MtmAhSgeKvUzYGTjOFmF/xfO3ksBAAUd3j0bmsAgA/9+I5XCsR/IRW/PLLdi2ocwsHY+VqdrH4p5kHN3EV2MrjtvhbrRYRFdRoYcux5EXupdTOIMz03GW4wbPJm90hKa2BbaWkzHF9hv6X5boPFrOP+7XqW01X7FVp9dGringEv8CPd+iNPqJLrISDjztnWVuRxpcoJbKEaObYR3DXNyQJ5nbGlrp8vmqRPC2nIJT6UqgE2Bqcap4a1NBVXVQ/zjCCJbDv44QGYWGCL0WIbxOvsWKWvd1otqHi07x8nOAhivoBI44q7UGIoGg0BTs8+EXbbpoAu4cNgLteipByEdtoXnYA7P+L3QLR7kBY5Qyc0bwI2UyE9JlxJMb/90701DMCcKuzvW14aEsVeu00j53UEUCV+i2lKMBZf67VIFQuUvgtUhzzJcvlMaElqh8OrPImRhUkMV9HMY2+qyrHc5CucDg="
      file: airsonic-main/target/airsonic.war
      skip_cleanup: true
      options:
        - prerelease: true
        - name: "Edge Release $TRAVIS_TAG"
      on:
        tags: true
    #- provider: script
    #  script: bash install/docker/dockerhub_push.sh
