name: 'CI (Maven)'

on:
  pull_request:
    branches: [ master ]

env:
  DEFAULT_MUSIC_FOLDER: /tmp/music
  EXCLUDED_TEST_GROUPS:

jobs:
  build:
    runs-on: ubuntu-latest
    env: ${{ matrix.cfg.env }}
    services: ${{ matrix.cfg.services }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.cfg.jdk }}
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - run: mkdir -p ${DEFAULT_MUSIC_FOLDER}
      - name: Build with Maven
        run: mvn -DexcludedGroups=${EXCLUDED_TEST_GROUPS} -Ddocker.testing.default-music-folder=${DEFAULT_MUSIC_FOLDER} verify -B -P integration-test

    strategy:
      fail-fast: false
      matrix:
        cfg:
          - jdk: 1.8
            services: {}
            env: {}
          - jdk: 9
            services: {}
            env: {}
          - jdk: 11
            services: {}
            env: {}
          - jdk: 13
            services: {}
            env: {}
          # external dbs
          - jdk: 11
            services:
              postgres:
                image: 'postgres:9.6-alpine'
                ports:
                  - 5432:5432
                env:
                  POSTGRES_PASSWORD: pass
            env:
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
              DatabaseConfigType: embed
              DatabaseConfigEmbedDriver: org.postgresql.Driver
              DatabaseConfigEmbedUrl: 'jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified'
              DatabaseConfigEmbedUsername: postgres
              DatabaseConfigEmbedPassword: pass
              DatabaseUsertableQuote: '"'
          - jdk: 11
            services:
              postgres:
                image: 'postgres:12.2-alpine'
                ports:
                  - 5432:5432
                env:
                  POSTGRES_PASSWORD: pass
            env:
              DatabaseConfigType: embed
              DatabaseConfigEmbedDriver: org.postgresql.Driver
              DatabaseConfigEmbedUrl: 'jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified'
              DatabaseConfigEmbedUsername: postgres
              DatabaseConfigEmbedPassword: pass
              DatabaseUsertableQuote: '"'
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
          #TODO for mysql,mariadb: add collation: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin when supported by github actions on services
          - jdk: 11
            services:
              mysql:
                image: 'mysql:5.7'
                ports:
                  - 3306:3306
                env:
                  MYSQL_DATABASE: airsonic
                  MYSQL_ROOT_PASSWORD: pass
            env:
              DatabaseConfigType: embed
              DatabaseConfigEmbedDriver: com.mysql.jdbc.Driver
              DatabaseConfigEmbedUrl: 'jdbc:mysql://localhost:3306/airsonic?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_bin'
              DatabaseConfigEmbedUsername: root
              DatabaseConfigEmbedPassword: pass
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
          - jdk: 11
            services:
              mysql:
                image: 'mysql:8.0'
                ports:
                  - 3306:3306
                env:
                  MYSQL_DATABASE: airsonic
                  MYSQL_ROOT_PASSWORD: pass
            env:
              DatabaseConfigType: embed
              DatabaseConfigEmbedDriver: com.mysql.jdbc.Driver
              DatabaseConfigEmbedUrl: 'jdbc:mysql://localhost:3306/airsonic?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_bin'
              DatabaseConfigEmbedUsername: root
              DatabaseConfigEmbedPassword: pass
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
          - jdk: 11
            services:
              mysql:
                image: 'mariadb:10.2'
                ports:
                  - 3306:3306
                env:
                  MYSQL_DATABASE: airsonic
                  MYSQL_ROOT_PASSWORD: pass
            env:
              DatabaseConfigType: embed
              DatabaseConfigEmbedDriver: org.mariadb.jdbc.Driver
              DatabaseConfigEmbedUrl: 'jdbc:mysql://localhost:3306/airsonic?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_bin'
              DatabaseConfigEmbedUsername: root
              DatabaseConfigEmbedPassword: pass
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
          - jdk: 11
            services:
              mysql:
                image: 'mariadb:10.5'
                ports:
                  - 3306:3306
                env:
                  MYSQL_DATABASE: airsonic
                  MYSQL_ROOT_PASSWORD: pass
            env:
              DatabaseConfigType: embed
              DatabaseConfigEmbedDriver: org.mariadb.jdbc.Driver
              DatabaseConfigEmbedUrl: 'jdbc:mysql://localhost:3306/airsonic?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_bin'
              DatabaseConfigEmbedUsername: root
              DatabaseConfigEmbedPassword: pass
              EXCLUDED_TEST_GROUPS: org.airsonic.player.util.EmbeddedTestCategory
