name: 'Test sign CI (Maven)'

on:
  create:
  push:
    branches: [ testing/** ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "github.repository == 'airsonic-advanced/airsonic-advanced' && startsWith(github.ref, 'testing/')"
    steps:
      - run: echo '12345' >> hello.txt
      - name: Import GPG Key for signing
        run: echo "${{ secrets.TEST_GPG_SIGNING_PRIVATE_KEY }}" | gpg --quiet --batch --yes --import
      - name: Sign artifacts
        run: |
          echo "${{ secrets.TEST_GPG_SIGNING_PASSPHRASE }}" | gpg --quiet --batch --yes --pinentry-mode loopback --clearsign --passphrase-fd 0 hello.txt;
      - name: Calculate tags
        id: tagcalc
        run: |
          # Create tag
          tag=test1;
          echo $tag;
          echo "::set-output name=tag::$tag"
      - name: Deploy to GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.tagcalc.outputs.tag }}
          name: Test Release ${{ steps.tagcalc.outputs.tag }}
          draft: true
          prerelease: true
          files: |
            hello.text.asc
